"""Enable PGVector and add embedding to Transcript

Revision ID: 6be6f5050bed
Revises: 19c2840a66d4
Create Date: 2026-03-19 19:20:18.305003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6be6f5050bed'
down_revision: Union[str, Sequence[str], None] = '19c2840a66d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('transcripts', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'embedding')
    # ### end Alembic commands ###
